### ISSUE TITLE
multimacd: ..........ERROR with HASSOS

### ISSUE THREAD

**Issue by DraqueB** [jens-maus/RaspberryMatic#1968]
### Describe the issue you are experiencing

First i have to thank you for your outstanding efforts! Great work.

Unfortunatly i cant get the RF modul working.

If i can try anything to help (even buying and testing of different hardware to sort things out i am more then ready to do so.

### Describe the behavior you expected

I should be able to teach in devices

### Steps to reproduce the issue

1. exactly followed your description - unfortunatly it doesnt work

...

### What is the version this bug report is based on?

 3.65.8.20220831

### Which base platform are you running?

odroid-n2 (ODROID N2/N2+)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
Mounting /data as /usr/local (Home Assistant Add-On): OK
Starting watchdog...
Identifying host system: oci, OK
Initializing RTC Clock: onboard, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.1, OK
Identifying Homematic RF-Hardware: ....HmRF: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-xhci-hcd.1.auto-1.1, HmIP: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-xhci-hcd.1.auto-1.1, OK
Updating Homematic RF-Hardware: HMIP-RFUSB: 4.4.18, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: ..........ERROR
Starting rfd: ERROR: /dev/mmd_bidcos missing, no BidCos-RF hardware found
Starting HMIPServer: ERROR: /dev/mmd_hmip missing
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: disabled
Starting Third-Party Addons: OK
find: /usr/local/etc/monit*.cfg: No such file or directory
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.65.8.20220831 (raspmatic_oci_arm64)
```

### Additional information

I also tryed with the latest snapshot (0930)

**Comment by jens-maus** [comment]
Known and fixed with the next nightly. Use search next time: https://github.com/jens-maus/RaspberryMatic/issues/1942

**Comment by DraqueB** [comment]
Thanks a lot.
Sorry, new to github - but promised for next time.

**Comment by bbadaboom** [comment]
Still happens to me with the snapshot build from today:
- RaspberryMatic CCU (snapshot): 3.65.11.20221001-342a485
- HA Version 2022.9.7
- Supervisor Version 2022.09.1.

I assume that RaspberryMatic snapshot version contains the "next nightly" which should fix the issue?

Here're the logs 
```
Mounting /data as /usr/local (Home Assistant Add-On): OK
Starting watchdog...
Identifying host system: oci, OK
Initializing RTC Clock: onboard, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.7, OK
Identifying Homematic RF-Hardware: ....HmRF: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-xhci-hcd.1.auto-1.1, HmIP: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-xhci-hcd.1.auto-1.1, OK
Updating Homematic RF-Hardware: HMIP-RFUSB: 4.4.18, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: creating new SSL cert... OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: ..............ERROR
Starting rfd: ERROR: /dev/mmd_bidcos missing, no BidCos-RF hardware found
Starting HMIPServer: ERROR: /dev/mmd_hmip missing
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: OK
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.65.11.20221001 (raspmatic_oci_arm64)
```

**Comment by jens-maus** [comment]
> I assume that RaspberryMatic snapshot version contains the "next nightly" which should fix the issue?

Yes, but your issue looks a bit different to the one mentioned here. Do you run HomeAssistantOS or run a HA Supervised installation on a different host OS? If so, then this is a different issue and I would suggest to switch to HomeAssistantOS instead because of hardware constraints.

**Comment by bbadaboom** [comment]
I'm running HomeAssistantOS on an Odroid N2+.

**Comment by DraqueB** [comment]
Same here:
Home Assistant 2022.9.7
Supervisor 2022.09.1
Operating System 9.0
Frontend 20220907.2 - latest
Plattform - Odroid N2+

Starting multimacd: ..............ERROR
Starting rfd: ERROR: /dev/mmd_bidcos missing, no BidCos-RF hardware found
Starting HMIPServer: ERROR: /dev/mmd_hmip missing

**Comment by jens-maus** [comment]
Hmm, anyone with a RaspberryPi who can reproduce that?!? @Baxxy13 ?

**Comment by mash727** [comment]
No not at the moment am waiting for the Homeassitant/raspberry update to
the version where the USB RF works again. I understood it should have been
yesterday.

Jens Maus ***@***.***> schrieb am Sa., 1. Okt. 2022, 14:41:

**Comment by jens-maus** [comment]
> No not at the moment am waiting for the Homeassitant/raspberry update to the version where the USB RF works again. I understood it should have been yesterday.

Release had been re-scheduled. Please, if you didn't test the latest RM snapshot yet, no need to reply or answer here. My question was if there **is** someone how can reproduce it and not if there is someone who **can't** reproduce it. Typical WhatsApp group kinda issue, I guess :)

**Comment by jens-maus** [comment]
> I'm running HomeAssistantOS on an Odroid N2+.

Ok, I could finally reproduce it here with my test ODROID N2+:

```
Starting multimacd: ..............ERROR
Starting rfd: ERROR: /dev/mmd_bidcos missing, no BidCos-RF hardware found
Starting HMIPServer: ERROR: /dev/mmd_hmip missing
```

However, with a RaspberryPi or OVA-based HomeAssistantOS everything seems to work fine. Thus, this seems to be a ODROID-N2 limited issue which needs some dedicated investigation+fixes.
