### ISSUE TITLE
HA add-on not starting on Odroid M1

### ISSUE THREAD

**Issue by linloen** [jens-maus/RaspberryMatic#2299]
### Describe the issue you are experiencing

HmIP-RFUSB error on start.
Start hangs on welcome screen, also without HmIP-RFUSB.

### Describe the behavior you expected

Add-on freezes on welcome screen.

### Steps to reproduce the issue

1. Install latest HA on Odroid M1.
2. Install HACS
3. Install RaspberryMatic add-on as per documentation.
4. Start add-on.

### What is the version this bug report is based on?

3.69.6.20230407

### Which base platform are you running?

ha-addon (HomeAssistant Add-on)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
3-04-25 08:11:01 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on ghcr.io/jens-maus/raspberrymatic with version 3.69.6.20230407
23-04-25 08:12:38 INFO (MainThread) [supervisor.host.info] Updating local host information
23-04-25 08:12:39 INFO (MainThread) [supervisor.host.services] Updating service information
23-04-25 08:12:39 INFO (MainThread) [supervisor.host.network] Updating local network information
23-04-25 08:12:40 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
23-04-25 08:12:40 INFO (MainThread) [supervisor.host.manager] Host information reload completed
23-04-25 08:13:28 INFO (SyncWorker_2) [supervisor.docker.interface] Stopping addon_de838cd8_raspberrymatic application
23-04-25 08:15:28 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Server disconnected
23-04-25 08:15:29 INFO (SyncWorker_2) [supervisor.docker.interface] Cleaning addon_de838cd8_raspberrymatic application
23-04-25 08:15:31 INFO (SyncWorker_7) [supervisor.docker.addon] Starting Docker add-on ghcr.io/jens-maus/raspberrymatic with version 3.69.6.20230407
23-04-25 08:18:32 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon RaspberryMatic CCU is unhealthy, restarting...
23-04-25 08:18:32 INFO (SyncWorker_5) [supervisor.docker.interface] Stopping addon_de838cd8_raspberrymatic application
23-04-25 08:20:32 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Server disconnected
23-04-25 08:20:33 INFO (SyncWorker_5) [supervisor.docker.interface] Cleaning addon_de838cd8_raspberrymatic application
23-04-25 08:20:35 INFO (SyncWorker_7) [supervisor.docker.addon] Starting Docker add-on ghcr.io/jens-maus/raspberrymatic with version 3.69.6.20230407
23-04-25 08:23:36 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon RaspberryMatic CCU is unhealthy, restarting...
23-04-25 08:23:36 INFO (SyncWorker_4) [supervisor.docker.interface] Stopping addon_de838cd8_raspberrymatic application
23-04-25 08:25:37 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_de838cd8_raspberrymatic application
23-04-25 08:25:39 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on ghcr.io/jens-maus/raspberrymatic with version 3.69.6.20230407
23-04-25 08:28:40 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon RaspberryMatic CCU is unhealthy, restarting...
23-04-25 08:28:40 INFO (SyncWorker_5) [supervisor.docker.interface] Stopping addon_de838cd8_raspberrymatic application
23-04-25 08:30:41 INFO (SyncWorker_5) [supervisor.docker.interface] Cleaning addon_de838cd8_raspberrymatic application
23-04-25 08:30:43 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on ghcr.io/jens-maus/raspberrymatic with version 3.69.6.20230407
23-04-25 08:33:44 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon RaspberryMatic CCU is unhealthy, restarting...
23-04-25 08:33:44 INFO (SyncWorker_6) [supervisor.docker.interface] Stopping addon_de838cd8_raspberrymatic application
23-04-25 08:35:45 INFO (SyncWorker_6) [supervisor.docker.interface] Cleaning addon_de838cd8_raspberrymatic application
23-04-25 08:35:47 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on ghcr.io/jens-maus/raspberrymatic with version 3.69.6.20230407
23-04-25 08:38:49 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon RaspberryMatic CCU is unhealthy, restarting...
```

### Additional information

Home Assistant 2023.4.6 
Supervisor 2023.04.1 
Operating System 10.0 
Frontend-versie: 20230411.1 - latest

**Comment by linloen** [comment]
RM add-on log:

Mounting /data as /usr/local (Home Assistant Add-On): OK
Starting watchdog...
Identifying host system: oci, OK
Initializing RTC Clock: onboard, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Saving 256 bits of creditable seed for next boot
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.2, OK
Identifying Homematic RF-Hardware: HmRF: n/a, HmIP: n/a, OK
Updating Homematic RF-Hardware: HMIP-RFUSB: =>4.4.18, ERROR ( != 4.4.18)
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: not required
Starting rfd: no BidCos-RF hardware found
Starting HMIPServer: ......OK
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: disabled
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.69.6.20230407 (raspmatic_oci_arm64)


Hardware info:
BUSNUM: '003'
DEVNAME: /dev/bus/usb/003/003
DEVNUM: '003'
DEVPATH: /devices/platform/fd8c0000.usb/usb3/3-1
DEVTYPE: usb_device
DRIVER: usb
ID_BUS: usb
ID_FOR_SEAT: usb-platform-fd8c0000_usb-usb-0_1
ID_MODEL: eQ-3_HmIP-RFUSB
ID_MODEL_ENC: eQ-3\x20HmIP-RFUSB
ID_MODEL_ID: c020
ID_PATH: platform-fd8c0000.usb-usb-0:1
ID_PATH_TAG: platform-fd8c0000_usb-usb-0_1
ID_REVISION: '0100'
ID_SERIAL: Silicon_Labs_eQ-3_HmIP-RFUSB_3014F711A000041F299ECBCA
ID_SERIAL_SHORT: 3014F711A000041F299ECBCA
ID_USB_INTERFACES: ':ff0000:'
ID_USB_MODEL: eQ-3_HmIP-RFUSB
ID_USB_MODEL_ENC: eQ-3\x20HmIP-RFUSB
ID_USB_MODEL_ID: c020
ID_USB_REVISION: '0100'
ID_USB_SERIAL: Silicon_Labs_eQ-3_HmIP-RFUSB_3014F711A000041F299ECBCA
ID_USB_SERIAL_SHORT: 3014F711A000041F299ECBCA
ID_USB_VENDOR: Silicon_Labs
ID_USB_VENDOR_ENC: Silicon\x20Labs
ID_USB_VENDOR_ID: 1b1f
ID_VENDOR: Silicon_Labs
ID_VENDOR_ENC: Silicon\x20Labs
ID_VENDOR_ID: 1b1f
MAJOR: '189'
MINOR: '258'
PRODUCT: 1b1f/c020/100
SUBSYSTEM: usb
TAGS: ':seat:'
TYPE: 0/0/0
USEC_INITIALIZED: '74792714248'

**Comment by ciB89** [comment]
I also have the same error on my Pi4 (does not find my HMIP-RFUSB anymore), I recently updated pivccu though to latest stable.

**Comment by ciB89** [comment]
> @ciB89
> 
> > I also have the same error on my Pi4 (does not find my HMIP-RFUSB anymore), I recently updated pivccu though to latest stable.
> 
> Sorry, these are two things (Pi4 and pivccu) that don't belong here! 1. this ticket/issue is about ODROID M1 support and 2. you are here in the "RaspberryMatic" project which is totally unrelated to piVCCU.

I was referring to the pivccu kernel modules which this project uses, and I also at least use the ha addon. It does not necessarily need to be connected, but who knows, maybe the information can be of use in the end..

**Comment by linloen** [comment]
Unfortunately latest version does not solve the problem.

Mounting /data as /usr/local (Home Assistant Add-On): OK
Starting watchdog...
Identifying host system: oci, OK
Initializing RTC Clock: onboard, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Saving 256 bits of creditable seed for next boot
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.4, OK
Identifying Homematic RF-Hardware: HmRF: n/a, HmIP: n/a, OK
Updating Homematic RF-Hardware: HMIP-RFUSB: =>4.4.18, ERROR ( != 4.4.18)
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: not required
Starting rfd: no BidCos-RF hardware found
Starting HMIPServer: ......OK
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: disabled
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.69.7.20230506 (raspmatic_oci_arm64)


RaspberryMatic still won't start.

**Comment by jens-maus** [comment]
> Unfortunately latest version does not solve the problem.

Of course not, because this ticket/issue is still open an not closed, thus not taken care of yet...

**Comment by jens-maus** [comment]
This issue should be solved with the HomeAssistantOS 10.3 release. See: https://github.com/home-assistant/operating-system/releases/tag/10.3

**Comment by linloen** [comment]
Thanks for the update.

Installed  HA OS 10.3 (still only available through beta channel).
Unfortunately add-on still does not start.

Mounting /data as /usr/local (Home Assistant Add-On): OK
Starting watchdog...
Identifying host system: oci, OK
Initializing RTC Clock: onboard, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Saving 256 bits of creditable seed for next boot
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.4, OK
Identifying Homematic RF-Hardware: ..sh: write error: Function not implemented
..HmRF: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-xhci-hcd.1.auto-1, HmIP: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-xhci-hcd.1.auto-1, OK
Updating Homematic RF-Hardware: HMIP-RFUSB: 4.4.18, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: ..............ERROR
Starting rfd: ERROR: /dev/mmd_bidcos missing, no BidCos-RF hardware found
Starting HMIPServer: ERROR: /dev/mmd_hmip missing
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: disabled
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.69.7.20230506 (raspmatic_oci_arm64)
