### ISSUE TITLE
wlan0 interface link down on Raspberry Pi 2B

### ISSUE THREAD

**Issue by Hypnos3** [jens-maus/RaspberryMatic#587]
**Describe the bug**
I have updated to 3.45.5.20190330 and get Monit WatchDog-Alarm "wlan0 interface link down" on every reboot.
This is may be technically right, because Raspberry Pi 2B has no hardware for WLAN, but it's annoying.

**To Reproduce**
1. See Alarm List

**Expected behavior**
No "wlan0 interface link down" for a Raspberry Pi without WLAN Hardware like 2B.

**System information (please complete the following information):**
 - RaspberryMatic 3.45.5.20190330 
 - Hardware RaspberryPi 2B

**Comment by jens-maus** [comment]
This alarm message should of course not be generated if the WiFi interface is disabled. So it seems in your case it is actually enabled. So please enter the following command and show the output:

```
/usr/sbin/rfkill list wlan
```

If this shows for "Soft blocked" AND "Hard blocked:" an output of "no" then it seems something is actually enabling your WiFi interface. If this is the case please check if you have a file `/etc/config/wpa_supplicant.conf` in your configuration and if yes, then delete this file as this will disable the WiFi interface, otherwise it will be enabled by default and thus `monit` is right to alarm you on the non working WiFi interface.

**Comment by Hypnos3** [comment]
I get following error:
```# /usr/sbin/rfkill list wlan
rfkill: cannot open /dev/rfkill: No such file or directory
rfkill: cannot read /dev/rfkill: Bad file descriptor
```
A `/etc/config/wpa_supplicant.conf` does not exists.

**Comment by jens-maus** [comment]
Ok, now I get it. This seems to be indeed a bug where I missed that on a system without WiFi the rfkill command returns an error. Thanks for the hint.

**Comment by hotroot** [comment]
Same for a Raspberry Pi 1 B+ which has no WiFi Hardware at all.

**Comment by jens-maus** [comment]
@hotroot As my last comment and the closed status of this ticket suggests: The issue should be solved already. So the next release will have this fixed. For the time being simply execute the following command to stop Monit from monitoring the `wlan0` interface:

```
monit unmonitor wlan0
```

**Comment by beerisgood** [comment]
Problem still (or again?) exist for my Pi 2B.

Pi is up2date with latest Raspbian:
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
Linux raspberrypi 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l

**Comment by piadam** [comment]
Same here. Just reinstalled a Pi2 and received these errors using the latest Raspbian.

**Comment by jatorres5** [comment]
I had the same issue, but i solved, just editing this file /etc/rc.local and add this line before the "exit 0" 

`rfkill unblock all `

save and reboot, no more errors.
