### ISSUE TITLE
hwclock: incorrect by 1 hour

### ISSUE THREAD

**Issue by trfrde** [jens-maus/RaspberryMatic#956]
**Describe the bug**
After syncing the hwclock (using a DS3231 rtc) to the ntp time, the hwclock is correct. After some seconds / minutes, the hwclock jumps 1 hour into the future.
This results in a time mismatch of the raspberrymatic if the ntp server is disconnected and the hwclock is used.

**Steps to reproduce the behavior**
The time after the two `date` commands is the actual time
```
root@homematic:/var/status# date
Tue Oct 20 20:14:51 CEST 2020

root@homematic:/var/status# /bin/setHWClock.sh

root@homematic:/var/status# hwclock --show --utc
Tue Oct 20 20:14:58 2020  0.000000 seconds

root@homematic:/var/status# hwclock --show --utc
Tue Oct 20 20:21:58 2020  0.000000 seconds

root@homematic:/var/status# hwclock --show --utc
Tue Oct 20 21:23:13 2020  0.000000 seconds

root@homematic:/var/status# date
Tue Oct 20 20:23:41 CEST 2020
```

**Expected behavior**
No time offset of the hwclock.

**Screenshots**
...

**System information:**
 - RaspberryMatic Version: 3.53.30.20200919
 - Used Hardware: RPi3B+; RTC module DS3231
 - Used HomeMatic RF-Module: HM-MOD-RPI-PCB

**Additional context**
Timezone (via GUI) is Europe/Berlin. Same behavior if CET/CEST +1/+2 is selected.
RTC clock DS3231 installed and working:
```
root@homematic:/var/status# i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- 57 -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- UU -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```
```
root@homematic:/var/status# cat /var/hm_mode
...
HM_RTC='mcp7941x'
```

**Comment by jens-maus** [comment]
Thanks for the report. This issue has been already fixed in the current development snapshot (see https://github.com/jens-maus/RaspberryMatic/commit/27eadf07c82e03e45ead8a1e2aecf9623d476dfe) and will be part of the next upcoming release.

**Comment by trfrde** [comment]
Today I installed  Raspberrymatic 3.53.30.20201024 (as an update). Unfortunately, I don't understand the behaviour of the hwclock (and I think something is still not working correctly):

```
root@homematic:/bin# hwclock -w --utc
```
```
root@homematic:~# date
Fri Oct 30 21:55:00 CET 2020

root@homematic:~# hwclock --show --utc
Fri Oct 30 21:55:01 2020  0.000000 seconds

root@homematic:~# date
Fri Oct 30 21:55:02 CET 2020
```
```
root@homematic:~# date
Fri Oct 30 21:59:03 CET 2020

root@homematic:~# hwclock --show --utc
Fri Oct 30 22:59:05 2020  0.000000 seconds

root@homematic:~# date
Fri Oct 30 21:59:07 CET 2020
```
Again, there is an offset of 1 hour between the ntp time and the hwclock after a little while.

**Comment by jens-maus** [comment]
You are right, there seems to be still some issue with chrony and the kernel RTC synchronization, which we have to address.

**Comment by jens-maus** [comment]
The latest commit should now hopefully fix all these issues for the next upcoming version.
